### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Johnny2buttons** [oRazeD/GrabDoc#1]
![image](https://user-images.githubusercontent.com/85197997/160672790-e93c0c51-61bd-4d90-9ce1-aa65fa512667.png)
maybe I'm wrong, but I have such a mistake =)

**Comment by oRazeD** [comment]
This is an old issue that was prematurely closed. This error should be fixed in the commit below:

https://github.com/oRazeD/GrabDoc/commit/244b21fa74acb1c9852e2686ca103e6942ed96f9
