### ISSUE TITLE
Pressing onto "Ambient Occlusion" preview - causes error.

### ISSUE THREAD

**Issue by nineteenss** [oRazeD/GrabDoc#10]
**Blender console error description:**
```
Python: Traceback (most recent call last):
  File "C:\Users\serge\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\GrabDoc\utils\node.py", line 502, in create_node_links
    node_group.inputs[input_name].default_value = \
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Normal" not found'
```

**Settings and scene preview:**
![{6A8ADBAA-9704-40AC-AA53-93556B52F7FD}](https://github.com/user-attachments/assets/6568845e-4a35-4703-b56b-442f4535d214)

**Error preview:**
![image](https://github.com/user-attachments/assets/3c5a0b29-1f33-487b-a07a-44bfbd8e732d)

**Reproduction (skip if downloaded blender project file):**
Blender 4.2.0+ > Setup Scene > Build up trimsheet or anything else on top of desctination area > Press "Ambient Occlusion Preview" > Voila, you got the error

**Blender project file instead of reproduction with existing error:**
[trim_baker.blend @ drive.google.com](https://drive.google.com/drive/folders/10lyI0PwC_q62uC1Zc1S6dYPjsIL_OUiK)

**Comment by oRazeD** [comment]
Hey @nineteenss, there's a chance the scene hasn't been initialized by GrabDoc properly, or you switched GrabDoc versions in the same project.

Does this issue still occur if you copy your objects to a new scene with GrabDoc set up?

**Comment by nineteenss** [comment]
Heya, @oRazeD. You were right, new setup ceased the problem. Then what makes this error occur? Anyways, thank you for the help.

![image](https://github.com/user-attachments/assets/daba56af-2068-482f-a894-cc785a574abd)

**Comment by oRazeD** [comment]
The most common case this can happen with is if you had created a GrabDoc scene, and later updated the add-on to a version where the internal referenced object/node group names had changed between versions. This doesn't happen super often, but was definitely part of more recent changes.

Glad I could help!
