### ISSUE TITLE
[Bug] IndexError in console 

### ISSUE THREAD

**Issue by Victor-IX** [oRazeD/GrabDoc#11]
# Issue Info

The following error is spammed in the Blender console:
```
Traceback (most recent call last):
  File "C:\Users\<USER>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\GrabDoc\ui.py", line 318, in poll
    baker = getattr(context.scene.gd, cls.ID)[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
```
This error appears when I open the N-panel.

# Setup
- Windows 11  
- Blender 4.2.4  
- GrabDoc 1.4.5 (Extension Platform)

**Comment by oRazeD** [comment]
Hey Victor, what happens when you open a fresh blend file and setup GrabDoc again?

This issue can happen for several reasons, but the most common (and unsolvable from my end) is that you had a previous version of GrabDoc installed in the same blend file, which created a conflict after updating.

**Comment by Victor-IX** [comment]
- Remove GrabDoc
- Restart Bledner
- Reinstall Grabdoc (no error in the console)
- Restart Blender (Error in the console when opening the N-Panel)

My blender settings are very up to date, I'm working on a setup tool to automaticly download extension addon... and I have this error after a fresh setup.
Here the list of the addon and extension I have install if it can help you:
- bl_ext.me_extensions.Cablerator
- bl_ext.me_extensions.CleanPanels
- bl_ext.me_extensions.ME_Blender_Toolbox
- bl_ext.me_extensions.NGonLoopSelect
- Boxcutter
- DECALmachine
- HOps
- MACHIN3tools
- polyhavenassets
- PowerSave
- ZenUV
- bl_ext.blender_org.align_tools
- bl_ext.blender_org.bool_tool
- bl_ext.blender_org.cell_fracture
- bl_ext.blender_org.copy_attributes_menu
- bl_ext.blender_org.edit_mesh_tools
- bl_ext.blender_org.extra_curve_objectes
- bl_ext.blender_org.extra_mesh_objects
- bl_ext.blender_org.io_scene_max
- bl_ext.blender_org.looptools
- bl_ext.blender_org.node_arrange

**Comment by Victor-IX** [comment]
The issue is coming from `clean panel`. I will check with them; it will probably be a fix on their end.

**Comment by oRazeD** [comment]
Keep me posted!

**Comment by kiruha228** [comment]
How to fix this?
```
Python: Traceback (most recent call last):
  File "C:\Users\<USER>\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\GrabDoc\operators\operators.py", line 182, in execute
    baker_init(self, context)
  File "C:\Users\<USER>\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\GrabDoc\utils\baker.py", line 935, in baker_init
    self.savedUseBloom = eevee.use_bloom
                         ^^^^^^^^^^^^^^^
AttributeError: 'SceneEEVEE' object has no attribute 'use_bloom'
```

**Comment by oRazeD** [comment]
Hey @kiruha228, this should be fixed in 2d4180d372b2c4d0afd65e86b30f9f45a830de38!

You can download the latest archive from this link: https://github.com/oRazeD/GrabDoc/archive/refs/heads/main.zip

**Comment by kiruha228** [comment]
@oRazeD  Thank you very much! I spent many hours to solve the problem, I wish I had thought of writing post here earlier...

**Comment by oRazeD** [comment]
Going to close this issue, please feel free to re-open or make a new one if the issues re-occur.

**Comment by StrawberrySmoothieDev** [comment]
Getting this crash again, seems to occur when undoing while grabdoc is active and toggling edit mode.

```bpy.ops.mesh.primitive_plane_add(size=2, calc_uvs=True, enter_editmode=False, align='WORLD', location=(0, 0, 0), rotation=(0, 0, 0), scale=(1, 1, 1))  # Operator
bpy.ops.grabdoc.scene_setup()  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.mesh.select_mode(use_extend=False, use_expand=False, type='VERT')  # Operator
bpy.ops.transform.translate(value=(-0.579677, 0.0945917, 0.664052), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=True, use_proportional_edit=False, proportional_edit_falloff='SMOOTH', proportional_size=1, use_proportional_connected=False, use_proportional_projected=False, snap=False, snap_elements={'INCREMENT'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False)  # Operator
bpy.ops.view3d.blenderkit_disclaimer_widget(message="Get beautiful spring models, HDRIs & scenes!", url="https://www.blenderkit.com/disclaimer/visit/spring-assets2026/?source=addon", fadeout_time=8, tip=False)  # Operator
bpy.ops.object.editmode_toggle()  # Operator

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION (0xc0000005)
Exception Address     : 0x00007FF645DB32A2
Exception Module      : blender.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] (action)  : 0x0000000000000000 (read)
	Parameters[1] (address) : 0x0000000000000018

...


# Python backtrace
  File "C:\Users\<NAME>\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\user_default\GrabDoc\ui.py", line 275 in poll
```
Windows 10, Blender 5.0.1, occurs with Grabdoc as the only addon.

Steps to reproduce:

- Open blank file
- Setup grabdoc scene
- Go to edit mode
- Move cube in edit mode
- Undo
- Exit edit mode
- Undo 2-3 times
- Crash
