### ISSUE TITLE
Issues with materials that have multiple material output nodes

### ISSUE THREAD

**Issue by Di5ina** [oRazeD/GrabDoc#2]
It appears that grabdoc will attach its material nodes to the first material output node in the material. This is a problem for materials that have different node groups for cycles and eevee. Further, the node tree will break if you swap the grabdoc node to the correct material output after you enter preview node.

A workaround I found is making sure that the 'original' material out node is the one set to eevee.

![Screenshot from 2022-09-04 18-06-57](https://user-images.githubusercontent.com/100454402/188335283-fdf71d66-5214-4d1d-85a3-786889f2eaa7.png)

**Comment by oRazeD** [comment]
Should be fixed with the commit below. Please open this issue back up or create a new one if the problem persists :)

https://github.com/oRazeD/GrabDoc/commit/9f72d852a8cfb5894af20f8b9edfee9ec2296f9d
