### ISSUE TITLE
Permission & View transforms error for Blender 4.0

### ISSUE THREAD

**Issue by DominoKorean** [oRazeD/GrabDoc#5]
Same as main release
main branch and dev branch

https://github.com/oRazeD/GrabDoc/assets/110039366/b4d2a17a-ad20-46f7-88d0-646dd7844df7

**Comment by DominoKorean** [comment]
I tried using the repository from the last pull request, and everything works fine except that the View Transform is set to Standard, which requires manual change.
https://github.com/LilithSilver/GrabDoc

**Comment by DominoKorean** [comment]
![image](https://github.com/oRazeD/GrabDoc/assets/110039366/367f0f2c-1b12-4ae2-80bc-d9ab0732772d)

The render button next to Preview doesn't work properly, but since rendering directly doesn't pose any problems, it seems there will be no issue in using it.

Yesterday, I used the latest version of the main branch in the same way, but at that time, none of the previews, except for Normal, worked properly.

**Comment by oRazeD** [comment]
Does your default export name have a space in it? Seems like path is attempting to export to a bad path thus the permissions error.

**Comment by oRazeD** [comment]
Recreated issue on my end and fixed in e8cfcf4
