### ISSUE TITLE
Channel Packing Textures

### ISSUE THREAD

**Issue by Kovadon** [oRazeD/GrabDoc#9]
Adding a feature to handle packing multiple renders to the RGBA channels of an output texture would be very handy

**Comment by oRazeD** [comment]
Hey @Kovadon, this feature should already be implemented.
![image](https://github.com/user-attachments/assets/34fc7bb4-200c-4b4d-a277-6f9745fa37b4)

**Comment by Kovadon** [comment]
oh i see, i'm on 1.4.3 and didn't see it, thanks :D
